### ISSUE TITLE
V2DL3 failing because IRF file defined for only one camera offset

### ISSUE THREAD

**Issue by leandrorizk** [VERITAS-Observatory/V2DL3#215] opened 2024-09-16 20:44 UTC
I am encountering an issue when trying to convert **soft2tel anasum.root** files (Eventdisplay) into **full-enclosure DL3 for UMa3** data. Out of 27 runs, only one (108868) is completed without error. For the rest, I get:

> RUN -> 109031
> python pyV2DL3/script/v2dl3_for_Eventdisplay.py --full-enclosure -f ./109031.anasum.root /raid/reedbuck/lrizk/Eventdisplay/Eventdisplay_AnalysisFiles_VTS/EffectiveAreas/effArea-v490-auxv01-CARE_June2020-Cut-NTel2-PointSource-Soft-TMVA-BDT-AP-DISP-V6_2023_2023s-ATM62-T1234.root ../../fullenc_DL3/109031.anasum.fits
> INFO:v2dl3: Converting to DL3 (full-enclosure:  True, point-like: False)
> INFO:v2dl3: Eventdisplay: anasum file ./109031.anasum.root
> INFO:v2dl3: Effective: area file /raid/reedbuck/lrizk/Eventdisplay/Eventdisplay_AnalysisFiles_VTS/EffectiveAreas/effArea-v490-auxv01-CARE_June2020-Cut-NTel2-PointSource-Soft-TMVA-BDT-AP-DISP-V6_2023_2023s-ATM62-T1234.root
> INFO:v2dl3: IRF axes force extrapolation: False
> INFO:v2dl3: Database FITS file: None
> INFO:v2dl3: Reconstruction type: EventDisplay
> INFO:v2dl3: Run number: 109031
> INFO:v2dl3: Number of events: 110160
> INFO:v2dl3: Number of Telescopes: 4
> INFO:v2dl3: Eventdisplay logfile not found in anasum root file. Quality flag set to 0
> INFO:v2dl3: Duration: 1689 (sec.) 28.15 (min)
> INFO:v2dl3: Ontime: 1569 (sec.) 26.15 (min)
> INFO:v2dl3: GTIs start and stop in second since run start: [0, 1440] [1320, 1689]
> INFO:v2dl3: Parameters used to query IRFs: az=279.72 deg, ze=31.20 deg, pedvar=7.7
> INFO:v2dl3: Extracting Full-enclosure IRFs for zenith: 31.2 deg, pedvar: 7.7
> INFO:v2dl3:     camera offset:  0.50,
> INFO:v2dl3:     zenith range of a given IRF: 0.00 - 60.00
> INFO:v2dl3:     pedvar range of a given IRF: 2.43 - 7.71
> ERROR:v2dl3: IRF used for interpolation must be defined for several offsets for full-enclosure conversion
> Traceback (most recent call last):
>   File "/raid/reedbuck/lrizk/V2DL3/pyV2DL3/script/v2dl3_for_Eventdisplay.py", line 150, in <module>
>     cli()
>   File "/raid/reedbuck/lrizk/envs/v2dl3Eventdisplay/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/raid/reedbuck/lrizk/envs/v2dl3Eventdisplay/lib/python3.12/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/raid/reedbuck/lrizk/envs/v2dl3Eventdisplay/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/raid/reedbuck/lrizk/envs/v2dl3Eventdisplay/lib/python3.12/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/raid/reedbuck/lrizk/V2DL3/pyV2DL3/script/v2dl3_for_Eventdisplay.py", line 132, in cli
>     datasource.fill_data(evt_filter=evt_filter, db_fits_file=db_fits_file)
>   File "/raid/reedbuck/lrizk/V2DL3/pyV2DL3/VtsDataSource.py", line 21, in fill_data
>     self.__fill_response__(**kwargs)
>   File "/raid/reedbuck/lrizk/V2DL3/pyV2DL3/eventdisplay/EventDisplayDataSource.py", line 63, in __fill_response__
>     self.__response__ = __fill_response__(
>                         ^^^^^^^^^^^^^^^^^^
>   File "/raid/reedbuck/lrizk/V2DL3/pyV2DL3/eventdisplay/fillRESPONSE.py", line 406, in __fill_response__
>     raise FullEnclosureOffsetAxisError
> pyV2DL3.eventdisplay.fillRESPONSE.FullEnclosureOffsetAxisError

This is not occurring for moderate2tel or for point-like options.

Investigating the file `effArea-v490-auxv01-CARE_June2020-Cut-NTel2-PointSource-Soft-TMVA-BDT-AP-DISP-V6_2023_2023s-ATM62-T1234.root`, I see that wobble angle offset is only ever defined at 0.5° ($\pm$ some small decimals). See image below. 

![W_off_T1234](https://github.com/user-attachments/assets/699b29f4-bcda-4518-8881-45c835c4b265)

This is the effective area file for all runs except 108868 (the successful one), which uses `effArea-v490-auxv01-CARE_June2020-Cut-NTel2-PointSource-Soft-TMVA-BDT-AP-DISP-V6_2023_2023s-ATM62-T234.root`. See image below. Note the difference in the filenames is only [...]-**T1234**.root vs [...]-**T234**.root.

![W_off_T234](https://github.com/user-attachments/assets/39007753-da3a-4ebd-93f2-20588392dffc)

Inspecting the DQM page, it seems that run 108868 is the only run from the runlist that drops T1 due to T1 pointing monitor crashing near the end of the run.

**Comment by GernotMaier** [comment] 2024-09-17 07:45
Thank for your reporting this. I can confirm this.

These epochs and cuts are affected:

- 2022_2023w and 2023_2023s
- 4-telescope IRFs (3-telescopes IRFs are good)
- soft point-source cuts
- AP cleaning only

The issue is on the IRF generation side and this means I have to rerun  the IRF production and then reprocess the DL3 files. This will take a couple of days.

**Comment by GernotMaier** [comment] 2024-09-30 07:57
Thanks a again for reporting this issue.

New IRFs for these epochs are generated and release with v490.8, see https://github.com/VERITAS-Observatory/EventDisplay_Release_v490/releases/tag/v490.8-v3.4

Closing this issue therefore. Please open a new one if you see further problems.

**Closed by GernotMaier** 2024-09-30 07:57 UTC
